language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.5-dev"
  - "nightly"
  - "pypy"
  - "pypy3"

os:
  - linux

install:
  - if [[ $TRAVIS_PYTHON_VERSION == 2.6 ]]; then pip install --use-mirrors unittest2; fi
  - pip install fuzzywuzzy
  - pip install python-levenshtein

script: nosetests -vv -w tests/
